apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bmp-sim-connectivity-bussiness-service
  namespace: dtag-dev
  labels:
    app: bmp-sim-connectivity-bussiness-service
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmp-sim-connectivity-bussiness-service
      version: latest
  template:
    metadata:
      name: bmp-sim-connectivity-bussiness-service
      labels:
        app: bmp-sim-connectivity-bussiness-service
        version: latest
    spec:
      containers:
      - name: bmp-sim-connectivity-bussiness-service
        image: 10.0.5.16:5000/bm/bmp-sim-connectivity-bussiness-service:latest
        args: ["--spring.profiles.active=onap"]
        imagePullPolicy: Always
      imagePullSecrets:
      - name: onap
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
        ports:
        - containerPort: 9087
